const product = [
    {
        id: 0,
        image1: '/assets/productos/stock/maicena.png',
        image2: '/assets/productos/sin-stock/maicena_sin-stock.jpg',
        title: 'Alfajor Maicena',
        stock: 'Sin Stock',
        price: '$1.000',
    },
    {
        id: 1,
        image1: '/assets/productos/stock/block.png',
        image2: '/assets/productos/sin-stock/block_sin-stock.jpg',
        title: 'Alfajor Block',
        stock: 'Sin Stock',
        price: '$1.100',
    },
    {
        id: 2,
        image1: '/assets/productos/stock/bonobon.png',
        image2: '/assets/productos/sin-stock/bonobon_sin-stock.jpg',
        title: 'Alfajor Bon o Bon',
        stock: 'Sin Stock',
        price: '$1.100',
    },
    {
        id: 3,
        image1: '/assets/productos/stock/fantoche.png',
        image2: '/assets/productos/sin-stock/fantoche_sin-stock.jpg',
        title: 'Alfajor Fantoche',
        stock: 'Sin Stock',
        price: '$900',
    },
    {
        id: 4,
        image1: '/assets/productos/stock/milka.png',
        image2: '/assets/productos/sin-stock/milka_sin-stock.jpg',
        title: 'Alfajor Milka',
        stock: 'Sin Stock',
        price: '$1.100',
    },
    {
        id: 5,
        image1: '/assets/productos/stock/alfajoroeropng.png',
        image2: '/assets/productos/sin-stock/alfajororeo_sin-stock.jpg',
        title: 'Alfajor Oreo',
        stock: 'Sin Stock',
        price: '$1.100',
    },
    {
        id: 6,
        image1: '/assets/productos/stock/pepitoalf.png',
        image2: '/assets/productos/sin-stock/pepitoalf_sin-stock.jpg',
        title: 'Alfajor Pepito',
        stock: 'Sin Stock',
        price: '$1.100',
    },
    {
        id: 7,
        image1: '/assets/productos/stock/tatinsimple.png',
        image2: '/assets/productos/sin-stock/tatinsimple_sin-stock.jpg',
        title: 'Tatin Blanco',
        stock: 'Sin Stock',
        price: '$350',
    },
    {
        id: 8,
        image1: '/assets/productos/stock/tatintriple.png',
        image2: '/assets/productos/sin-stock/tatintriple_sin-stock.jpg',
        title: 'Tatin Blanco Triple',
        stock: 'Sin Stock',
        price: '$900',
    },
    {
        id: 9,
        image1: '/assets/productos/stock/terrabusi.png',
        image2: '/assets/productos/sin-stock/terrabusi_sin-stock.jpg',
        title: 'Alfajor Terrabusi',
        stock: 'Sin Stock',
        price: '$900',
    },
    {
        id: 10,
        image1: '/assets/productos/stock/trishot.png',
        image2: '/assets/productos/sin-stock/trishot_sin-stock.jpg',
        title: 'Alfajor Trishot',
        stock: 'Sin Stock',
        price: '$1.100',
    },
    {
        id: 11,
        image1: '/assets/productos/stock/tofinegro.png',
        image2: '/assets/productos/sin-stock/tofinegro_sin-stock.jpg',
        title: 'Tofi Negro',
        stock: 'Sin Stock',
        price: '$550',
    },
    {
        id: 12,
        image1: '/assets/productos/stock/guaymallenb.png',
        image2: '/assets/productos/sin-stock/guaymallenb_sin-stock.jpg',
        title: 'Guaymallen Blanco',
        stock: 'Sin Stock',
        price: '$700',
    },
    {
        id: 13,
        image1: '/assets/productos/stock/guaymallenn.png',
        image2: '/assets/productos/sin-stock/guaymallenn_sin-stock.jpg',
        title: 'Guaymallen Negro',
        stock: 'Sin Stock',
        price: '$700',
    },
    {
        id: 14,
        image1: '/assets/productos/stock/agua.png',
        image2: '/assets/productos/sin-stock/agua_sin-stock.jpg',
        title: 'Agua',
        stock: 'Sin Stock',
        price: '$1.000',
    },
    {
        id: 15,
        image1: '/assets/productos/stock/aquapera.png',
        image2: '/assets/productos/sin-stock/aquapera_sin-stock.jpg',
        title: 'Aquarius Pera',
        stock: 'Sin Stock',
        price: '$1.300',
    },
    {
        id: 16,
        image1: '/assets/productos/stock/aquapemoelo.png',
        image2: '/assets/productos/sin-stock/aquapemoelo_sin-stock.jpg',
        title: 'Aquarius Pomelo',
        stock: 'Sin Stock',
        price: '$1.300',
    },
    {
        id: 17,
        image1: '/assets/productos/stock/levitepomelo.png',
        image2: '/assets/productos/sin-stock/levitepomelo_sin-stock.jpg',
        title: 'Levite Pomelo',
        stock: 'Sin Stock',
        price: '$1.300',
    },
    {
        id: 18,
        image1: '/assets/productos/stock/baggiodurazno.png',
        image2: '/assets/productos/sin-stock/baggiodurazno_sin-stock.jpg',
        title: 'Baggio Durazno',
        stock: 'Sin Stock',
        price: '$800',
    },
    {
        id: 19,
        image1: '/assets/productos/stock/baggiomanzana.png',
        image2: '/assets/productos/sin-stock/baggiomanzana_sin-stock.jpg',
        title: 'Baggio Manzana',
        stock: 'Sin Stock',
        price: '$800',
    },
    {
        id: 20,
        image1: '/assets/productos/stock/baggiomulti.png',
        image2: '/assets/productos/sin-stock/baggiomulti_sin-stock.jpg',
        title: 'Baggio Multifruta',
        stock: 'Sin Stock',
        price: '$800',
    },
    {
        id: 21,
        image1: '/assets/productos/stock/baggionaranja.png',
        image2: '/assets/productos/sin-stock/baggionaranja_sin-stock.jpg',
        title: 'Baggio Naranja',
        stock: 'Sin Stock',
        price: '$800',
    },
    {
        id: 22,
        image1: '/assets/productos/stock/mixmanzana.png',
        image2: '/assets/productos/sin-stock/mixmanzana_sin-stock.jpg',
        title: 'Barra Cereal Mix Manzana',
        stock: '',
        price: '$1.000',
    },
    {
        id: 23,
        image1: '/assets/productos/stock/mixchocoalmendra.png',
        image2: '/assets/productos/sin-stock/mixchocoalmendra_sin-stock.jpg',
        title: 'Barra Cereal Mix Choco/Almendra',
        stock: '',
        price: '$1.000',
    },
    {
        id: 24,
        image1: '/assets/productos/stock/bulldogsandia.png',
        image2: '/assets/productos/sin-stock/bulldogsandia_sin-stock.jpg',
        title: 'Bull dog Sandia',
        stock: 'Sin Stock',
        price: '$650',
    },
    {
        id: 25,
        image1: '/assets/productos/stock/bulldogtuttilimon.png',
        image2: '/assets/productos/sin-stock/bulldogtuttilimon_sin-stock.jpg',
        title: 'Bull dog Tutti Limon',
        stock: 'Sin Stock',
        price: '$650',
    },
    {
        id: 26,
        image1: '/assets/productos/stock/beldentfruti.png',
        image2: '/assets/productos/sin-stock/beldentfruti_sin-stock.jpg',
        title: 'Beldent Frutilla',
        stock: 'Sin Stock',
        price: '$800',
    },
    {
        id: 27,
        image1: '/assets/productos/stock/beldentmenta.png',
        image2: '/assets/productos/sin-stock/beldentmenta_sin-stock.jpg',
        title: 'Beldent Menta',
        stock: 'Sin Stock',
        price: '$800',
    },
    {
        id: 28,
        image1: '/assets/productos/stock/toplinementa.png',
        image2: '/assets/productos/sin-stock/toplinementa_sin-stock.jpg',
        title: 'TopLine Menta',
        stock: 'Sin Stock',
        price: '$700',
    },
    {
        id: 29,
        image1: '/assets/productos/stock/toplinefruti.png',
        image2: '/assets/productos/sin-stock/toplinefruti_sin-stock.jpg',
        title: 'TopLine Frutilla',
        stock: 'Sin Stock',
        price: '$700',
    },
    {
        id: 30,
        image1: '/assets/productos/stock/hall.png',
        image2: '/assets/productos/sin-stock/hall_sin-stock.jpg',
        title: `Hall's Menta`,
        stock: 'Sin Stock',
        price: '$700',
    },
    {
        id: 31,
        image1: '/assets/productos/stock/chupetinblue.png',
        image2: '/assets/productos/sin-stock/chupetinblue_sin-stock.jpg',
        title: 'Chupetin Blueberry',
        stock: 'Sin Stock',
        price: '$200',
    },
    {
        id: 32,
        image1: '/assets/productos/stock/chupetincereza.png',
        image2: '/assets/productos/sin-stock/chupetincereza_sin-stock.jpg',
        title: 'Chupetin Cereza',
        stock: 'Sin Stock',
        price: '$200',
    },
    {
        id: 33,
        image1: '/assets/productos/stock/chupetinsurtido.png',
        image2: '/assets/productos/sin-stock/chupetinsurtido_sin-stock.jpg',
        title: 'Chupetin Surtido',
        stock: 'Sin Stock',
        price: '$200',
    },
    {
        id: 34,
        image1: '/assets/productos/stock/chupetinuvatutti.png',
        image2: '/assets/productos/sin-stock/chupetinuvatutti_sin-stock.jpg',
        title: 'Chupetin Uva/Tutti',
        stock: 'Sin Stock',
        price: '$200',
    },
    {
        id: 35,
        image1: '/assets/productos/stock/cocacola.png',
        image2: '/assets/productos/sin-stock/cocacola_sin-stock.jpg',
        title: 'Coca Cola',
        stock: 'Sin Stock',
        price: '$1.300',
    },
    {
        id: 36,
        image1: '/assets/productos/stock/cocacolazero.png',
        image2: '/assets/productos/sin-stock/cocacolazero_sin-stock.jpg',
        title: 'Coca Cola Zero',
        stock: 'Sin Stock',
        price: '1.000',
    },
    {
        id: 37,
        image1: '/assets/productos/stock/sprite.png',
        image2: '/assets/productos/sin-stock/sprite_sin-stock.jpg',
        title: 'Sprite',
        stock: 'Sin Stock',
        price: '$1.300',
    },
    {
        id: 38,
        image1: '/assets/productos/stock/spritelata.png',
        image2: '/assets/productos/sin-stock/spritelata_sin-stock.jpg',
        title: 'Sprite Lata',
        stock: 'Sin Stock',
        price: '$900',
    },
    {
        id: 39,
        image1: '/assets/productos/stock/fanta.png',
        image2: '/assets/productos/sin-stock/fanta_sin-stock.jpg',
        title: 'Fanta',
        stock: 'Sin Stock',
        price: '$1.000',
    },
    {
        id: 40,
        image1: '/assets/productos/stock/formischoco.png',
        image2: '/assets/productos/sin-stock/formischoco_sin-stock.jpg',
        title: 'Formis Chocolate',
        stock: '',
        price: '$1.300',
    },
    {
        id: 41,
        image1: '/assets/productos/stock/formisfrutilla.png',
        image2: '/assets/productos/sin-stock/formisfrutilla_sin-stock.jpg',
        title: 'Formis Frutilla',
        stock: 'Sin Stock',
        price: '$1.300',
    },
    {
        id: 42,
        image1: '/assets/productos/stock/galletitaspepito.png',
        image2: '/assets/productos/sin-stock/galletitaspepito_sin-stock.jpg',
        title: 'Galletitas Pepito',
        stock: 'Sin Stock',
        price: '$1.300',
    },
    {
        id: 43,
        image1: '/assets/productos/stock/tortitaschoco.png',
        image2: '/assets/productos/sin-stock/tortitaschoco_sin-stock.jpg',
        title: 'Tortitas Chocolate',
        stock: 'Sin Stock',
        price: '$900',
    },
    {
        id: 44,
        image1: '/assets/productos/stock/chocolinas.png',
        image2: '/assets/productos/sin-stock/chocolinas_sin-stock.jpg',
        title: 'Chocolinas',
        stock: '',
        price: '$1.500',
    },
    {
        id: 45,
        image1: '/assets/productos/stock/macucas.png',
        image2: '/assets/productos/sin-stock/macucas_sin-stock.jpg',
        title: 'Macucas',
        stock: 'Sin Stock',
        price: '$900',
    },
    {
        id: 46,
        image1: '/assets/productos/stock/oreos.png',
        image2: '/assets/productos/sin-stock/oreos_sin-stock.jpg',
        title: 'Oreos',
        stock: 'Sin Stock',
        price: '$1.300',
    },
    {
        id: 47,
        image1: '/assets/productos/stock/turron.png',
        image2: '/assets/productos/sin-stock/turron_sin-stock.jpg',
        title: 'Turron',
        stock: 'Sin Stock',
        price: '$1.000',
    },
    {
        id: 48,
        image1: '/assets/productos/stock/gomitasmogul.png',
        image2: '/assets/productos/sin-stock/gomitasmogul_sin-stock.jpg',
        title: 'Gomitas Mogul',
        stock: 'Sin Stock',
        price: '$600',
    },
    {
        id: 49,
        image1: '/assets/productos/stock/gomitasmogulacida.png',
        image2: '/assets/productos/sin-stock/gomitasmogulacida_sin-stock.jpg',
        title: 'Gomitas Mogul Acidas',
        stock: 'Sin Stock',
        price: '$650',
    },
    {
        id: 50,
        image1: '/assets/productos/stock/lays.png',
        image2: '/assets/productos/sin-stock/lays_sin-stock.jpg',
        title: 'Lays Clasicas',
        stock: 'Sin Stock',
        price: '$2.600',
    },
    {
        id: 51,
        image1: '/assets/productos/stock/laysjamon.png',
        image2: '/assets/productos/sin-stock/laysjamon_sin-stock.jpg',
        title: 'Lays Jamon Serrano',
        stock: 'Sin Stock',
        price: '$2.600',
    },
    {
        id: 52,
        image1: '/assets/productos/stock/laysketchup.png',
        image2: '/assets/productos/sin-stock/laysketchup_sin-stock.jpg',
        title: 'Lays Ketchup',
        stock: 'Sin Stock',
        price: '$2.600',
    },
    {
        id: 53,
        image1: '/assets/productos/stock/agridulce.png',
        image2: '/assets/productos/sin-stock/agridulce_sin-stock.jpg',
        title: '9 de Oro Agridulce',
        stock: 'Sin Stock',
        price: '$1.350',
    },
    {
        id: 54,
        image1: '/assets/productos/stock/grasa.png',
        image2: '/assets/productos/sin-stock/grasa_sin-stock.jpg',
        title: '9 de Oro Grasa',
        stock: '',
        price: '$1.350',
    },
    {
        id: 55,
        image1: '/assets/productos/stock/pepas9oro.png',
        image2: '/assets/productos/sin-stock/pepas9oro_sin-stock.jpg',
        title: 'Pepas 9 de Oro',
        stock: 'Sin Stock',
        price: '$1.250',
    },
    {
        id: 56,
        image1: '/assets/productos/stock/donsaturdulce.png',
        image2: '/assets/productos/sin-stock/donsaturdulce_sin-stock.jpg',
        title: 'Don Satur Dulce',
        stock: 'Sin Stock',
        price: '$1.350',
    },
    {
        id: 57,
        image1: '/assets/productos/stock/donsatursalada.png',
        image2: '/assets/productos/sin-stock/donsatursalada_sin-stock.jpg',
        title: 'Don Satur Salada',
        stock: 'Sin Stock',
        price: '$1.350',
    },
    {
        id: 58,
        image1: '/assets/productos/stock/pepastrio.png',
        image2: '/assets/productos/sin-stock/pepastrio_sin-stock.jpg',
        title: 'Pepas Trio',
        stock: 'Sin Stock',
        price: '$1.700',
    },
    {
        id: 59,
        image1: '/assets/productos/stock/rocklets.png',
        image2: '/assets/productos/sin-stock/rocklets_sin-stock.jpg',
        title: 'Rocklets',
        stock: 'Sin Stock',
        price: '$650',
    },
    {
        id: 60,
        image1: '/assets/productos/stock/saladixcalabresa.png',
        image2: '/assets/productos/sin-stock/saladixcalabresa_sin-stock.jpg',
        title: 'Saladix Calabresa',
        stock: 'Sin Stock',
        price: '$1.000',
    },
    {
        id: 61,
        image1: '/assets/productos/stock/saladixjamon.png',
        image2: '/assets/productos/sin-stock/saladixjamon_sin-stock.jpg',
        title: 'Saladix Jamon',
        stock: 'Sin Stock',
        price: '$1.000',
    },
    {
        id: 62,
        image1: '/assets/productos/stock/saladixpizza.png',
        image2: '/assets/productos/sin-stock/saladixpizza_sin-stock.jpg',
        title: 'Saladix Pizza',
        stock: 'Sin Stock',
        price: '$1.000',
    },
    {
        id: 63,
        image1: '/assets/productos/stock/te.png',
        image2: '/assets/productos/sin-stock/te_sin-stock.jpg',
        title: 'Té Saquito',
        stock: '',
        price: '$100',
    },
    {
        id: 64,
        image1: '/assets/productos/stock/matecodico.png',
        image2: '/assets/productos/sin-stock/matecodico_sin-stock.jpg',
        title: 'Mate Cocido',
        stock: '',
        price: '$100',
    },
    {
        id: 65,
        image1: '/assets/productos/stock/cafe.png',
        image2: '/assets/productos/sin-stock/cafe_sin-stock.jpg',
        title: 'Café en Saquito',
        stock: '',
        price: '$200',
    },
];

const categories = product;

document.getElementById('searchBar').addEventListener('keyup', (e) => {
    const searchData = e.target.value.toLowerCase();
    const filteredData = categories.filter((item) => {
        return (
            item.title.toLowerCase().includes(searchData)
        )
    })
    displayItem(filteredData)
});

const displayItem = (items) => {
    document.getElementById('main').innerHTML = items.map((item) => {
        let { image1, image2, title, stock, price } = item;
        let image = stock !== "" ? image2 : image1;
        return (
            `<div class="producto">
                <img src="${image}" alt="${title}">
                <h2>${title}</h2>
                ${stock !== "" ? `<p class="stock">${stock}</p>` : ""}
                <p>${price}</p>
            </div>`
        )
    }).join('')
};

displayItem(categories);